### ISSUE TITLE
GameSolver almost perfect but it guessed too many time

### ISSUE THREAD

**Issue by taveratch** [OOP2018/guessing-game-masty123#1]
upperbound = 2
It guessed 4 times but there are only two numbers to be guessed. [1,2]
The maximum count should be 2

**Comment by masty123** [comment]
Thank for the advice, used the Bisection Algorithm now.

**Comment by taveratch** [comment]
But it stuck in infinite loop when upperbound = 1 or 2

**Comment by masty123** [comment]
Fixed the upperBound problem, thanks
