### ISSUE TITLE
logic error for termination condition

### ISSUE THREAD

**Issue by taveratch** [OOP2018/guessing-game-masty123#6]
should not define like this
https://github.com/OOP2018/guessing-game-masty123/blob/master/src/GameSolver.java#L13-L14

You already have a variable that indicates whether a guess is correct or not `guess() returns boolean`.  Please use that variable as the termination condition.

**Comment by masty123** [comment]
Already used the guess() method, thanks for the advice.

**Comment by taveratch** [comment]
Well, You are calling guess() twice per loop. This affects number of count.

**Comment by masty123** [comment]
I'm now used only guess() on the while loop, thanks
